### ISSUE TITLE
No edit once published (SharePoint Online)

### ISSUE THREAD

**Issue by mrsbeata** [ephox/textboxio-docs#1]
Until yesterday the webpart was working fine. It's setup as it is supposed to and the users are happy. We are only using it for one site Collection, the webart itself says it's working fine. 

Version | 1.0.0.0
Release date | november 2017

I can add it as a webpart on a modern web page and work it fine. But once it's been published it can't be edited. I tried to add Another web part on the same web page and it coudl be edited. 

Some can work it in Internet Explorer and some can't work it in any webbrowser. There are PC computers with Win 10. If not up to date, only one release from it. It's automatically done.

**Comment by tinydylan** [comment]
Hi,

Apologies for the late response to this query - it slipped through the cracks of our process and wasn't picked up.

If this issue relates to our product Textbox.io, then the project has been sunset in favour of TinyMCE, as described in [this article](https://www.tiny.cloud/blog/the-future-of-textbox-io-and-rich-text-editing-solutions-from-tiny)

If you encounter any issues with TinyMCE, you may log them against the [TinyMCE GitHub project](https://github.com/tinymce/tinymce/issues) or by contacting [Tiny Support](https://support.tiny.cloud/hc/en-us).

Once again, apologies for responding to your query so late.

Kind regards,

Dylan Just
Tiny
